package com.spring.ghost.model;

import java.io.Serializable;
import java.util.Date;

public class Images implements Serializable {
    private Integer id;

    private String imageName;

    private String imageTag;

    private String gitBranch;

    private String gitMessage;

    private String host;

    private String port;

    private String codeRegistry;

    private String pullAddress;

    private Date createdAt;

    private Date updatedAt;

    private String command;

    private String dockerfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.id
     *
     * @return the value of images.id
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.id
     *
     * @param id the value for images.id
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_name
     *
     * @return the value of images.image_name
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_name
     *
     * @param imageName the value for images.image_name
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_tag
     *
     * @return the value of images.image_tag
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getImageTag() {
        return imageTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_tag
     *
     * @param imageTag the value for images.image_tag
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setImageTag(String imageTag) {
        this.imageTag = imageTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.git_branch
     *
     * @return the value of images.git_branch
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getGitBranch() {
        return gitBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.git_branch
     *
     * @param gitBranch the value for images.git_branch
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setGitBranch(String gitBranch) {
        this.gitBranch = gitBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.git_message
     *
     * @return the value of images.git_message
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getGitMessage() {
        return gitMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.git_message
     *
     * @param gitMessage the value for images.git_message
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setGitMessage(String gitMessage) {
        this.gitMessage = gitMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.host
     *
     * @return the value of images.host
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.host
     *
     * @param host the value for images.host
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.port
     *
     * @return the value of images.port
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.port
     *
     * @param port the value for images.port
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.code_registry
     *
     * @return the value of images.code_registry
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getCodeRegistry() {
        return codeRegistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.code_registry
     *
     * @param codeRegistry the value for images.code_registry
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setCodeRegistry(String codeRegistry) {
        this.codeRegistry = codeRegistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.pull_address
     *
     * @return the value of images.pull_address
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getPullAddress() {
        return pullAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.pull_address
     *
     * @param pullAddress the value for images.pull_address
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setPullAddress(String pullAddress) {
        this.pullAddress = pullAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.created_at
     *
     * @return the value of images.created_at
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.created_at
     *
     * @param createdAt the value for images.created_at
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.updated_at
     *
     * @return the value of images.updated_at
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.updated_at
     *
     * @param updatedAt the value for images.updated_at
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.command
     *
     * @return the value of images.command
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.command
     *
     * @param command the value for images.command
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setCommand(String command) {
        this.command = command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.dockerfile
     *
     * @return the value of images.dockerfile
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public String getDockerfile() {
        return dockerfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.dockerfile
     *
     * @param dockerfile the value for images.dockerfile
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    public void setDockerfile(String dockerfile) {
        this.dockerfile = dockerfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imageName=").append(imageName);
        sb.append(", imageTag=").append(imageTag);
        sb.append(", gitBranch=").append(gitBranch);
        sb.append(", gitMessage=").append(gitMessage);
        sb.append(", host=").append(host);
        sb.append(", port=").append(port);
        sb.append(", codeRegistry=").append(codeRegistry);
        sb.append(", pullAddress=").append(pullAddress);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", command=").append(command);
        sb.append(", dockerfile=").append(dockerfile);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}