package com.spring.ghost.mapper;

import com.spring.ghost.model.Images;
import com.spring.ghost.model.ImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int countByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int deleteByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int insertSelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    List<Images> selectByExampleWithBLOBs(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    List<Images> selectByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    Images selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int updateByExample(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int updateByPrimaryKeySelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Sat Dec 29 17:56:18 CST 2018
     */
    int updateByPrimaryKey(Images record);
}